### ISSUE TITLE
Upload a new release to Hackage

### ISSUE THREAD

**Issue by pepeiborra** [Avi-D-coder/implicit-hie-cradle#2]
Now that ghcide depends on implicit-hie-cradle, we need a release with the changes in #1 to be uploaded to Hackage before we can release ghcide 0.4.0

**Comment by Avi-D-coder** [comment]
Will do

**Comment by Avi-D-coder** [comment]
https://hackage.haskell.org/package/implicit-hie-cradle-0.2.0.0
